import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val com_github_johnrengelman_shadow_gradle_plugin: String =
            "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val org_jetbrains_kotlin_js_gradle_plugin: String =
            "org.jetbrains.kotlin.js:org.jetbrains.kotlin.js.gradle.plugin:_"

    public const val kotlin_stdlib_js: String = "org.jetbrains.kotlin:kotlin-stdlib-js:_"

    public const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test"
}
